### ISSUE TITLE
[EXPIRED] Windows binary

### ISSUE THREAD

**Issue by sergeevabc** [moinakg/pcompress#49]
Dear Moinak Ghosh,

Back in 2012 you were preoccupied with Linux version of Pcompress as you claimed at Encode’s forum. Four years passed since, any chance of Windows 64-bit release for those of us who do not compile?

**Comment by moinakg** [comment]
Hello,

Yes a long time has passed since I did anything with pcompress. I was
totally involved with a start-up which sucked all my time and energy.
I am still with the start-up but things are settling down slowly so I will
start looking back at this again.
The trouble is my windows pc has gone bad so I will have to use vmware p2v
tricks to migrate the xp installation from a hard disk to a vm.

The other option is to get a new windows 10 license.

Regards,
Moinak.

**Comment by sergeevabc** [comment]
Any progress?
